import type { UserIndicatorDefinition } from '../types/indicator';
import {
  getAllStoredIndicators,
  type StoredIndicator,
} from './indicatorStorage';

/**
 * Parses stored indicator code and creates a UserIndicatorDefinition
 * 
 * Uses new Function() for runtime evaluation since the code is:
 * 1. Generated by AI following strict contract rules
 * 2. Stored in user's own local storage (user-controlled)
 * 3. Validated before execution
 * 4. Has no network or DOM access within the function scope
 */
function parseIndicatorCode(code: string, metadata: StoredIndicator): UserIndicatorDefinition {
  try {
    // Create a sandboxed function with minimal scope
    // The code should export a UserIndicatorDefinition
    const fn = new Function(`
      'use strict';
      ${code}
      return typeof exports !== 'undefined' ? exports : 
             typeof module !== 'undefined' && module.exports ? module.exports :
             typeof indicator !== 'undefined' ? indicator :
             null;
    `);

    const result = fn();

    if (!result || typeof result !== 'object') {
      throw new Error('Code must export a UserIndicatorDefinition object');
    }

    // Validate required fields
    if (typeof result.id !== 'string') {
      throw new Error('Indicator must have a string "id" field');
    }
    if (typeof result.name !== 'string') {
      throw new Error('Indicator must have a string "name" field');
    }
    if (typeof result.calculate !== 'function') {
      throw new Error('Indicator must have a "calculate" function');
    }

    // Merge with metadata from storage
    const definition: UserIndicatorDefinition = {
      id: result.id,
      name: result.name,
      description: result.description ?? metadata.description,
      defaultVisible: result.defaultVisible ?? metadata.defaultVisible ?? false,
      params: result.params ?? metadata.params,
      calculate: result.calculate,
    };

    return definition;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to parse indicator code: ${message}`);
  }
}

/**
 * Loads all stored indicators and converts them to UserIndicatorDefinition objects
 * 
 * Invalid indicators are skipped with console warnings
 */
export function loadStoredIndicators(): UserIndicatorDefinition[] {
  const stored = getAllStoredIndicators();
  const loaded: UserIndicatorDefinition[] = [];

  for (const item of stored) {
    try {
      const definition = parseIndicatorCode(item.code, item);
      loaded.push(definition);
    } catch (error) {
      console.warn(
        `Failed to load stored indicator "${item.id}":`,
        error instanceof Error ? error.message : error
      );
    }
  }

  return loaded;
}

/**
 * Loads a single stored indicator by ID
 */
export function loadStoredIndicatorById(id: string): UserIndicatorDefinition | null {
  const stored = getAllStoredIndicators();
  const item = stored.find(i => i.id === id);

  if (!item) return null;

  try {
    return parseIndicatorCode(item.code, item);
  } catch (error) {
    console.warn(
      `Failed to load stored indicator "${id}":`,
      error instanceof Error ? error.message : error
    );
    return null;
  }
}

/**
 * Validates indicator code without executing it
 * Performs basic syntax and structure checks
 */
export function validateIndicatorCode(code: string): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check for forbidden patterns
  const forbiddenPatterns = [
    { pattern: /\bimport\b/g, message: 'Cannot use import statements' },
    { pattern: /\brequire\b/g, message: 'Cannot use require()' },
    { pattern: /\bfetch\b/g, message: 'Cannot use fetch()' },
    { pattern: /\bXMLHttpRequest\b/g, message: 'Cannot use XMLHttpRequest' },
    { pattern: /\bWebSocket\b/g, message: 'Cannot use WebSocket' },
    { pattern: /\blocalStorage\b/g, message: 'Cannot use localStorage' },
    { pattern: /\bsessionStorage\b/g, message: 'Cannot use sessionStorage' },
    { pattern: /\bdocument\./g, message: 'Cannot use document API' },
    { pattern: /\bwindow\./g, message: 'Cannot use window API' },
    { pattern: /\beval\s*\(/g, message: 'Cannot use eval()' },
    { pattern: /\bFunction\s*\(/g, message: 'Cannot use Function constructor' },
    { pattern: /\basync\s+function\b/g, message: 'Cannot use async functions' },
    { pattern: /\bawait\b/g, message: 'Cannot use await' },
  ];

  for (const { pattern, message } of forbiddenPatterns) {
    if (pattern.test(code)) {
      errors.push(message);
    }
  }

  // Check for required exports
  if (!code.includes('exports') && !code.includes('module.exports') && !code.includes('indicator')) {
    errors.push('Code must export a UserIndicatorDefinition');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Creates a template for a new indicator
 */
export function createIndicatorTemplate(
  id: string,
  name: string,
  description?: string
): string {
  return `// User-defined indicator: ${name}
// ${description ?? 'Custom indicator'}

const indicator = {
  id: '${id}',
  name: '${name}',
  description: '${description ?? ''}',
  defaultVisible: false,
  params: [
    // Define parameters here if needed
    // {
    //   key: 'period',
    //   label: 'Period',
    //   type: 'number',
    //   defaultValue: 20,
    //   min: 1,
    //   max: 200,
    //   step: 1,
    // },
  ],
  calculate({ klines, params }) {
    // Your indicator calculation logic here
    
    return {
      series: [
        // Define your series here
        // {
        //   id: 'main',
        //   name: '${name}',
        //   type: 'line',
        //   pane: 'price',
        //   color: '#38bdf8',
        //   lineWidth: 2,
        //   data: klines.map(k => ({
        //     time: k.date,
        //     value: k.close,
        //   })),
        // },
      ],
      // Optional: add signals
      // signals: [],
      // Optional: add hover fields
      // fields: [],
    };
  },
};

// Export the indicator
if (typeof exports !== 'undefined') {
  exports.default = indicator;
} else if (typeof module !== 'undefined') {
  module.exports = indicator;
}
`;
}
