import type { UserStrategyDefinition } from '../types/strategy';
import type { StoredStrategy } from './strategyStorage';
import {
  getAllStoredStrategies,
  getStoredStrategy,
} from './strategyStorage';

/**
 * Parses stored strategy code and creates a UserStrategyDefinition
 *
 * Uses new Function() for runtime evaluation since the code is:
 * 1. Generated by AI following strict contract rules
 * 2. Stored in user's own local storage (user-controlled)
 * 3. Validated before execution
 * 4. Has no network or DOM access within the function scope
 */
function parseStrategyCode(code: string, metadata: StoredStrategy): UserStrategyDefinition {
  try {
    // Create a sandboxed function with minimal scope
    // The code should export a UserStrategyDefinition
    const fn = new Function(`
      'use strict';
      ${code}
      return typeof exports !== 'undefined' ? exports :
             typeof module !== 'undefined' && module.exports ? module.exports :
             typeof strategy !== 'undefined' ? strategy :
             null;
    `);

    const result = fn();

    if (!result || typeof result !== 'object') {
      throw new Error('Code must export a UserStrategyDefinition object');
    }

    // Validate required fields
    if (typeof result.id !== 'string') {
      throw new Error('Strategy must have a string "id" field');
    }
    if (typeof result.name !== 'string') {
      throw new Error('Strategy must have a string "name" field');
    }
    if (typeof result.decide !== 'function') {
      throw new Error('Strategy must have a "decide" function');
    }

    // Merge with metadata from storage
    const definition: UserStrategyDefinition = {
      id: result.id,
      name: result.name,
      description: result.description ?? metadata.description,
      defaultSelected: result.defaultSelected ?? metadata.defaultSelected ?? false,
      params: result.params ?? metadata.params,
      availableIndicators: result.availableIndicators ?? metadata.availableIndicators,
      requiredIndicators: result.requiredIndicators ?? metadata.requiredIndicators,
      requiresChanLun: result.requiresChanLun ?? metadata.requiresChanLun,
      decide: result.decide,
    };

    return definition;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to parse strategy code: ${message}`);
  }
}

/**
 * Loads all stored strategies and converts them to UserStrategyDefinition objects
 *
 * Invalid strategies are skipped with console warnings
 */
export function loadStoredStrategies(): UserStrategyDefinition[] {
  const stored = getAllStoredStrategies();
  const loaded: UserStrategyDefinition[] = [];

  for (const item of stored) {
    try {
      const definition = parseStrategyCode(item.code, item);
      loaded.push(definition);
    } catch (error) {
      console.warn(
        `Failed to load stored strategy "${item.id}":`,
        error instanceof Error ? error.message : error
      );
    }
  }

  return loaded;
}

/**
 * Loads a single stored strategy by ID
 */
export function loadStoredStrategyById(id: string): UserStrategyDefinition | null {
  const item = getStoredStrategy(id);

  if (!item) return null;

  try {
    return parseStrategyCode(item.code, item);
  } catch (error) {
    console.warn(
      `Failed to load stored strategy "${id}":`,
      error instanceof Error ? error.message : error
    );
    return null;
  }
}

/**
 * Validates strategy code without executing it
 * Performs basic syntax and structure checks
 */
export function validateStrategyCode(code: string): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check for forbidden patterns
  const forbiddenPatterns = [
    { pattern: /\bimport\b/g, message: 'Cannot use import statements' },
    { pattern: /\brequire\b/g, message: 'Cannot use require()' },
    { pattern: /\bfetch\b/g, message: 'Cannot use fetch()' },
    { pattern: /\bXMLHttpRequest\b/g, message: 'Cannot use XMLHttpRequest' },
    { pattern: /\bWebSocket\b/g, message: 'Cannot use WebSocket' },
    { pattern: /\blocalStorage\b/g, message: 'Cannot use localStorage' },
    { pattern: /\bsessionStorage\b/g, message: 'Cannot use sessionStorage' },
    { pattern: /\bdocument\./g, message: 'Cannot use document API' },
    { pattern: /\bwindow\./g, message: 'Cannot use window API' },
    { pattern: /\beval\s*\(/g, message: 'Cannot use eval()' },
    { pattern: /\bFunction\s*\(/g, message: 'Cannot use Function constructor' },
    { pattern: /\basync\s+function\b/g, message: 'Cannot use async functions' },
    { pattern: /\bawait\b/g, message: 'Cannot use await' },
  ];

  for (const { pattern, message } of forbiddenPatterns) {
    if (pattern.test(code)) {
      errors.push(message);
    }
  }

  // Check for required exports
  if (!code.includes('exports') && !code.includes('module.exports') && !code.includes('strategy')) {
    errors.push('Code must export a UserStrategyDefinition');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Creates a template for a new strategy
 */
export function createStrategyTemplate(
  id: string,
  name: string,
  description?: string
): string {
  return `// User-defined strategy: ${name}
// ${description ?? 'Custom strategy'}

const strategy = {
  id: '${id}',
  name: '${name}',
  description: '${description ?? ''}',
  defaultSelected: false,
  params: [
    // Define parameters here if needed
    // {
    //   key: 'period',
    //   label: 'Period',
    //   type: 'number',
    //   defaultValue: 20,
    //   min: 1,
    //   max: 200,
    //   step: 1,
    // },
  ],
  decide({ klines, currentIndex, currentKline, account, position, trades, params, chanlun, currency, initialCash }) {
    // Available inputs:
    //   klines       - Array of kline data (oldest to newest, up to currentIndex)
    //   currentIndex - Zero-based index of currentKline in klines
    //   currentKline - Current kline { date, open, high, low, close, volume, amount }
    //   account      - { initialCash, cash, equity, currency }
    //   position     - { shares, averageCost, marketValue, unrealizedPnl, unrealizedPnlPercent }
    //   trades       - Previously executed trade snapshots
    //   currency     - Currency string (e.g. 'CNY')
    //   initialCash  - Initial cash amount
    //
    // [params]  - Strategy params + computed indicator values (flat key-value pairs):
    //   Strategy params defined in the params[] array above (READ-ONLY -- define them there).
    //   Indicator values AUTO-INJECTED at each step (access via params.MA5, params.BOLL_UP, etc.):
    //     Built-in: MA5, MA10, MA20, MA60, BOLL_UP/MID/LOW, MACD_DIF/DEA/MACD
    //     User-defined: params.{seriesName} (series names defined by the indicator's calculate output)
    //   Example: params.MA5 > params.MA20
    //
    // [chanlun] - ChanLun analysis { mergedKlines, fractions, strokes, segments, hubs }
    //   Always provided.

    return { action: 'HOLD' };
  },
};

// Export the strategy
if (typeof exports !== 'undefined') {
  exports.default = strategy;
} else if (typeof module !== 'undefined') {
  module.exports = strategy;
}
`;
}
